version: '3'
volumes:
  dbt_workshop_data:
services:
  dbt-workshop-db:
    container_name: dbt-workshop-db
    image: postgres:16.2
    ports:
      - '9675:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - 'dbt_workshop_data:/var/lib/postgresql/data'
