name: "dbt_workshop"
version: "1.0.0"

profile: "dbt_workshop"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

quoting:
  database: false
  schema: false
  identifier: false

seeds:
  enabled: true
